### ISSUE TITLE
[Request] Completely remove journalbeat book.

### ISSUE THREAD

**Issue by andresrc** [elastic/observability-docs#1174]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

After #1173 , we should completely remove the journalbeat book in 8.0. This might require some additional adjustments and / or redirects.

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

*(We need to have a contact person in the product/development team to provide information about how the item to be documented works - this can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

@nimarezainia 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

8.0

## Stakeholders

*(Please list any stakeholders for this issue.)*

@elastic/elastic-agent-data-plane

**Comment by nimarezainia** [comment]
I am not sure what we need to provide if it's being removed.

Where is a good place to mention that the journalbeat functionality is being provided by Filebeat? Would we still keep Journalbeat section and have this blurb inside that section.

**Comment by andresrc** [comment]
This issue is for 8.0 - in 7.16 we will keep the book and add the reference to the functionality being part of functionbeat. Please see #1173

**Comment by dedemorton** [comment]
Closing this request because the Journalbeat Reference was moved to the "Legacy" section of the docs for 7.16: https://www.elastic.co/guide/index.html

![image](https://user-images.githubusercontent.com/14206422/148847845-eb0bbf20-dabd-48d3-b13f-a8ccaff88d6c.png)

We've also added a header to the 7.16 docs that says:

![image](https://user-images.githubusercontent.com/14206422/148847979-70ee3f26-390e-47f2-9a50-163c5782e14a.png)
