### ISSUE TITLE
[APM] Document custom ingest pipelines

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1226]
### Related dev issue

* https://github.com/elastic/package-spec/issues/129

### Background

As of 8.0: The Fleet-managed ingest policy will be overwritten on reinstall/upgrade. Users can define their own custom ingest pipeline if needed, but they need to make sure that they also call the package-provided pipeline.

### Details

1. Fleet adds ingest pipelines for the APM integration using index templates that include pipeline index settings. 
2. Elasticsearch uses the data view in these index templates to match pipelines to APM data streams.
  As an example, the index template `traces-apm`, matches `traces-apm-*` data streams and assigns the `"traces-apm-7.16.0"` pipeline: 

  <img width="606" alt="Screen Shot 2021-10-29 at 1 15 07 PM" src="https://user-images.githubusercontent.com/5618806/139496414-89ea3078-3dd8-4c26-9766-80a299dd9694.png">

3. This Fleet-managed index template ⬆️ will be overwritten on reinstall/upgrade.

Assuming the above is correct, then I see three scenarios:

### Workarounds

1. A user can edit the Fleet-managed index template to point to a new pipeline, ensuring the following are true:
  a. ensure the package-provided pipeline is also called
  b. know that the index template will be overwritten on install/upgrade

2. A user can edit the default pipeline directly, like the `"traces-apm-7.16.0"` pipeline, ensuring the following are true:
  a. the package-provided pipelines are still included (first!)
  b. know that their edits will be overwritten on install/upgrade

### Documentaiton ideas

The following snippet was removed from https://github.com/elastic/apm-server/pull/6940.

```
[float]
[id="custom-pipelines{append-legacy}"]
=== Add a custom ingest pipeline

IMPORTANT: Fleet-managed index templates are overwritten on reinstall/upgrade.
Any customizations to index pipelines are not persisted when upgrading.
When editing {fleet}-managed index templates, ensure that the package-provided pipeline is still called.

// tutorial would be something like this:
. Find the pipeline **Stack Management** > **Index Management** > **Index Templates** > `traces-apm`.
. **Settings** >
+
[source,json]
----
{
  "index": {
    "default_pipeline": "traces-apm-{version}"
  }
}
----

// Edit default
. **Stack Management** > **Ingest Pipelines** > Search for +traces-apm-{version}+.
. **Manage** > **Edit** to edit the default pipeline.

// Add custom pipeline
. **Stack Management** > **Ingest Pipelines** > **Create pipeline**
. Create it
. **Stack Management** > **Ingest Pipelines** > Search for +traces-apm-{version}+.
. **Manage** > **Edit** to edit the default pipeline. Add the new pipeline as the final step.
```

### Links 'n stuff

* More context: https://github.com/elastic/apm-server/pull/6378#discussion_r738911907.

**Comment by bmorelli25** [comment]
> I'm wondering if we should be documenting this. Not being able to edit pipelines in a way that persists is a known issue, but we don't know how much of a pain that is yet. By documenting the workaround so prominently we may not learn that.

That was Andrew, with a thumbs up from Silvia in https://github.com/elastic/apm-server/pull/6940#discussion_r782735208. Holding off on documenting this for now.

**Comment by bmorelli25** [comment]
When we're ready to document custom ingest pipelines, we also need to remove the commented-out content added in https://github.com/elastic/apm-server/pull/8043.

**Comment by simitt** [comment]
Following https://github.com/elastic/observability-docs/issues/1936, we should document the support of custom ingest pipelines but also their current limitations. 

From 8.4 on, the apm ingest pipelines reference a non-existing, unversioned, custom processor. If existent, the custom processor is run last in the pipeline, before the _final_pipeline_ is run. The processor is unversioned, and therefore will be persisted across version updates. 

For example, the `traces-apm-8.4.0` pipeline references the `traces-apm@custom` processor:
<img width="536" alt="Screenshot 2022-08-01 at 09 01 43" src="https://user-images.githubusercontent.com/5555349/182091179-822e8919-ca2e-4147-a023-2ac5ff64a46c.png">

This can be used for additional annotations or data processing.

For `metrics` it can also be used to direct events to a datastream with a different `dataset`. 

<img width="545" alt="Screenshot 2022-08-01 at 09 19 27" src="https://user-images.githubusercontent.com/5555349/182095844-b1d6bc2e-09be-4bcc-a9c4-f783d71f8eb0.png">

The API Keys used to write to Elasticsearch have very limited privileges. The privileges are a bit more lose on the metrics dataset, since we allow dynamic data stream creation for splitting metrics by default. Other apm data streams (`traces-apm.*` or `logs-apm.*`) currently lack privileges to write to any other data streams. Attempts would be failing with an error message such as:

```
failed to index event (security_exception): action [indices:admin/auto_create] is unauthorized for API key id [RzVTRIIB4facokgKjivy] of user [elastic/fleet-server] on indices [traces-apm.custom-default], this action is granted by the index privileges [auto_configure,create_index,manage,all]
```

### Limitations
* _internal_ metrics (`metrics-apm.internal-<namespace>`) cannot be redirected to a different data stream 

* No support for sending `traces-apm.*` or `logs-apm.*` data to a different data stream when using Fleet managed APM Server.  Writing to a different data stream for `metrics` is possible 

Related to the limitations, see also https://github.com/elastic/kibana/issues/134971
