### ISSUE TITLE
[Request] correction needed in docs about ability to modify the Fleet Server policy when on ESS Cloud

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#1283]
## Description

Per Dede, I'm picking this issue out of a PR discussion, and logging it separately for follow up, here:
https://github.com/elastic/observability-docs/pull/1274#discussion_r753586507

tl;dr; we need to take out the section in:
 docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc 
...that cites the ability:
"To turn on {fleet-server} monitoring in the agent policy:"

## Collaboration
@dede, the code changes to make this inability more clear in the UI are quite new and Jen has confirmed intention. 
@nimarezainia was pinged prior for his agreement to remove, i'm pulling him in here for that again, too.

## Suggested Target Release
7..16

## Stakeholders
Fleet team

**Comment by dedemorton** [comment]
@EricDavisX Thanks for creating this issue. So just to clarify: since you cannot turn these options on, I'm assuming Fleet Server monitoring is not available on Elastic Cloud (and maybe not even needed).

It sounds like this topic is still valid (and needed) for Fleet Server running elsewhere. Is that correct?

I will remove the cloud steps, but should I make it clear in the intro that this topic does not apply to Fleet Server managed by cloud?

**Comment by EricDavisX** [comment]
@dedemorton hi.  yes, it is valid for self-managed stack deploys.  I'd say the topic is good, but we should not cite it can be done on cloud.  cheers
