### ISSUE TITLE
Provide more clarity around custom beat generator deprecation

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#1444]
## Provide more clarity around custom beat generator deprecation

From 8.0 the code that is used to generator custom beats will no longer be available for use. We have modified the docs already (https://www.elastic.co/guide/en/beats/devguide/8.0/community-beats.html) however more needs to be done to articulate what a users' options are in this regard. 

I suggest the following to be added to https://www.elastic.co/guide/en/beats/devguide/8.0/community-beats.html):

"
Custom Beat **generator** code is deprecated from 8.0 release on wards. 
This is the helper tool that allowed bootstrapping of a developer's custom Beats.  Open source community **can** still develop their own Beats to address their specific and targeted use cases. Custom Beat Generator tool is still available for use in 7.16 / 7.17 versions if there’s a need to create a Beat from scratch.  Developers can generate their custom Beat and upgrade its various components to 8.x releases.

It should be noted that Elastic does not provide warranty or support for community-sourced Beats.

"

## Collaboration

- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@nimarezainia 

## Suggested Target Release

8.0

## Stakeholders

fyi  @jlind23 @ruflin @kvch

**Comment by nimarezainia** [comment]
Hi @ollyhowell, can i move this to the todo column? thx

**Comment by ollyhowell** [comment]
Thanks @nimarezainia , still catching up 'this year' and hadn't seen this but have moved along and will have a chat with the team on scheduling

**Comment by dedemorton** [comment]
The statement "no longer be available for use" sounds like removal, not deprecation. Are we removing the actual generator code, too? (IMO, if we haven't, we should.) 

I think it's weird to provide documentation for capabilities that are not available, so I'm wondering if we should remove the content in 8.0 instead of marking it as deprecated.

Can you look through and identify which topics (if any) should be removed from the dev guide in 8.0? 
https://www.elastic.co/guide/en/beats/devguide/8.0/index.html

We can still have a topic that tells users to go to the 7.16 (or 7.17) docs for instructions.

We should also look for places in the docs where we encourage users to contribute community beats (might have already done that, but we should double check).

**Comment by jlind23** [comment]
Backlog grooming - @ollyhowell @nimarezainia What should we do with this issue?
