### ISSUE TITLE
[Request][Fleet] Account for removal of superuser requirement to access UI

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#1488]
## Description

Account for removal of superuser requirement to access UI, as implemented in 8.1 via https://github.com/elastic/kibana/issues/108252.

At minimum this page:
https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html

## Collaboration

- The docs team will lead producing the content

**Contact Person:** @criamico 

## Suggested Target Release

8.1

## Stakeholders

Fleet UI team

**Comment by joshdover** [comment]
We also should update the relevant row in the Beats v Agent comparison table here: https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

**Comment by mostlyjason** [comment]
@joshdover can we also document the privileges users need to use Fleet & Elastic Agent? I'm thinking something equivalent to https://www.elastic.co/guide/en/beats/filebeat/7.16/feature-roles.html. In addition to the Kibana privileges Fleet and Integrations, they also need Kibana privileges for Dashboards. They also need index privileges for common data streams, particularly elastic_agent data streams. Dede might need some guidance on what these should be.

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang 

We have validated the related links for the docs changes and our observations are shared below:
1. https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html

- Changes reflected properly under Privileges section :
"Kibana user with All privileges on Fleet and Integrations. Since many Integrations assets are shared across spaces, users need the Kibana privileges in all spaces."

2. https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

- Allow non-superusers to manage assets and agents section is updated with required  info as per mentioned under file changed.

3. https://www.elastic.co/guide/en/beats/filebeat/7.16/feature-roles.html
- No updates were observed at above page for fleet access requirements.

@dedemorton can you please confirm changes to validate on above page.

Thanks
QAS

**Comment by dedemorton** [comment]
I'm not sure why item 3 is on this list. We do not document Fleet in the Beats documentation. The other links look right. thanks.
