### ISSUE TITLE
Update "What is an integration"

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1491]
Update the integrations [get started](https://docs.elastic.co/en/integrations) content based on the internal integrations FAQ document.

Internal link, sorry: https://docs.google.com/document/d/1k7x9UwhAZLXGG4uwXTVT_HZD38Q34qgOdszXmDAY6ic

**Comment by dedemorton** [comment]
Should we make this a meta issue instead of focusing on the integrations content? After we finalize the terminology around integrations, we need to make changes across the library.

@ollyhowell Do you know if we're close to finalizing the terminology around integrations? The status of the google doc says, "Ready to review." I don't think we should make content updates until we've finalized the decisions in that document. WDYT?
