### ISSUE TITLE
[Request] Document how to use logstash in Fleet managed mode

### ISSUE THREAD

**Issue by nchaulet** [elastic/observability-docs#1691]
## Description 

To use logstash in Fleet the user will have to generate a bunch of certificate for mutual TLS, we should document how to do so similar to https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html

The documentation will be linked from here in the Fleet UI 

<img width="500" alt="Screen Shot 2022-03-18 at 9 43 10 AM" src="https://user-images.githubusercontent.com/1336873/159014016-928238b0-e718-4dfd-aff8-35b76dedd105.png">

And it will server to populate the certificate and certificate input here

<img width="500" alt="Screen Shot 2022-03-18 at 9 44 20 AM" src="https://user-images.githubusercontent.com/1336873/159014072-a875dfca-b283-46cb-bf78-fa879244f867.png">

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

**Contact Person:**

@nchaulet 

## Suggested Target Release

The feature will be available in 8.2.0

**Comment by nimarezainia** [comment]
@dedemorton I don't see this on the docs project board. I wanted to make sure that we are prioritizing Logstash support in 8.2 as it's a highly sought after feature. 

Also it needs to be marked Beta. I will follow up with an email on the details. thx

**Comment by nchaulet** [comment]
The instructions QA team created to test  the logstash feature it could probably help on what we need to document

```
Tips to follow:

- USE LICENSE PLATINUM.

- For windows Add Port 8220 for Fleet Server and 5044 for Logstash to Inbound rules in Windows Advanced Firewall.

- Logstash certificate key must be in pkcs8 format

Steps followed:

1. Setup a self-managed environment.

2. Install Fleet Server on self-managed kibana.

3. Create 3 certs ca, client and logstash with below commands:

elasticsearch-certutil ca --pem
elasticsearch-certutil cert --name logstash --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem
elasticsearch-certutil cert --name client --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem

4. Convert the logstash key to pkcs8 as it is the only format supported by logstash:

openssl pkcs8 -inform PEM -in logstash.key -topk8 -nocrypt -outform PEM -out logstash.pkcs8.key

For this use a linux machine.

5. Create logstash output-`My Logstash Output`(could be any):

Add logstash hosts: xxxx:5044 (machine ip)

Add below certs:

In Server SSL certificate we added- ca certificate.
In Client SSL certificate we added- client certificate.
In Client SSL certificate SSL key we added- client certificate key.

6. Added required configuration in pipelines.yml and created elastic-agent-pipeline.conf.

pipelines.yml:

- pipeline.id: elastic-agent-pipeline
  path.config: "C:\elk\logstash\config\elastic-agent-pipeline.conf"

elastic-agent-pipeline.conf:

input {
  elastic_agent {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["C:\elk\elasticsearch\ca\ca.crt"]
    ssl_certificate => "C:\elk\elasticsearch\logstash\logstash.crt"
    ssl_key => "C:\elk\elasticsearch\logstash\logstash.pkcs8.key"
    ssl_verify_mode => "force_peer"
  }
}

output {
  elasticsearch {
    hosts => "https://xxxx:9200"
    api_key => "xxxx:xxxx"
    data_stream => true
    ssl => true
    cacert => "C:\elk\logstash\config\http_ca.crt"
  }
}

Here- for cacert use the cert available under "C:\elk\elasticsearch\config\certs\http_ca.crt".

7. Run logstash from bin using below command:

logstash -f  C:\elk\logstash\config\elastic-agent-pipeline.conf

8. Create a new policy with integration output selected as- `My Logstash Output`.

9. Run Agent install command for second agent.

10. Observe data for System integration for this installed agent:
```

**Comment by joshdover** [comment]
@nchaulet As you indicated above, the designs of this project intended that the "View Documentation" button in the Logstash output UI would direct the user to a page that would help them configure the SSL certificates. In testing it's been clear that this is pretty necessary for users to be successful with this feature.

If this doc doesn't get published before 8.2.0 is released, it'd be nice for a the button to still work once it does get released. Right now the button just links to the overall Fleet & Agent guide. Would it be possible to use a redirect of some sort? Not sure if the docs website supports this, but worst case we could use an `ela.st` shortlink that we could update after the release is published.

I also wonder if we should start on a draft to help jump start this effort.

cc @jen-huang @kpollich

**Comment by kpollich** [comment]
Pasting my notes from the last few days of setting up a test environment for Logstash output in 8.2.0. As you can probably tell, this is a very involved process. Some key friction points for me:

- The actual cert generation process. Took a few tries to actually generate the proper certs in the formats Elasticsearch and Logstash were expecting
- Communication between local services and Dockerized ones - doing this entirely in a Dockerized environment would likely be more manageable, but I don't know how feasible that would be since we need to rely on generating service tokens, etc before we can start up Fleet Server or Agent. Maybe two different `docker-compose` files?

---

## Download Logstash + Elasticsearch + Kibana snapshot

- Download Logstash from https://snapshots.elastic.co/8.2.0-c56d8262/downloads/logstash/logstash-8.2.0-SNAPSHOT-darwin-x86_64.tar.gz
- Download Elasticsearch from https://snapshots.elastic.co/8.2.0-c56d8262/downloads/elasticsearch/elasticsearch-8.2.0-SNAPSHOT-darwin-x86_64.tar.gz
- Download Kibana from https://snapshots.elastic.co/8.2.0-4df380a5/downloads/kibana/kibana-8.2.0-SNAPSHOT-darwin-x86_64.tar.gz

## Add some records to your host file

This is optional, but it can make generating certificates easier or more convenient in some cases. This is a recommendation from this [blog post](https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash).

```
# /etc/hosts

# Add the section below

# Elastic Stuff
127.0.0.1 kibana.local logstash.local elasticsearch.local
# End Elastic Stuff
```

## Generate SSL Certificates

Use the `elasticsearch-certutil` tool to generate SSL certificates for secure communication between Logstash and Elasticsearch.

```bash
# From your Elasticsearch snapshot directory

$ ./bin/elasticsearch-certutil http

# Respond "no" when prompted to create a CSR, then provide your hostnames and IP addresses e.g. `elasticsearch.local`, `localhost`, `127.0.0.1` and `192.168.65.2`
# Unzip the resulting `.zip` archive and place its contents in `config/certs`

# Generate a fingerprint for the Elasticsearch CA `pem` file, and store it somewhere you can reference later
$ openssl x509 -fingerprint -sha256 -in ./config/certs/kibana/elasticsearch-ca.pem

# Extract only the "cert" portion from the CA cert
$ openssl pkcs12 -info -in ./config/certs/ca/ca.p12 -nokeys -out ./config/certs/ca/ca.cert

# Remove the colons and downcase the SHA fingerprint generated, e.g.
$ node
> const str = 'AB:78:21:5B:FE:4C:54:ED:A8:B3:09:9B:9E:9D:C0:C3:1F:A2:9C:14:4A:28:A2:DF:0E:DC:A3:8F:E6:C1:31:C0'
> str.toLowerCase().replaceAll(':', '')
'ab78215bfe4c54eda8b3099b9e9dc0c31fa29c144a28a2df0edca38fe6c131c0'
> .exit

# Generate logstash certificate + pkcs8 key
$ ./bin/elasticsearch-certutil cert --name logstash --ca ./config/certs/ca/ca.p12 --dns elasticsearch.local --pem
$ unzip logstash.zip -d ./config/certs
$ openssl pkcs8 -inform PEM -in ./config/certs/logstash/logstash.key -topk8 -nocrypt -outform PEM -out ./config/certs/logstash/logstash.pkcs8.ke
```

## Configure + Run Elasticsearch

Add the following to your `config/elasticsearch.yml` file

```yaml
network.host: elasticsearch.local

xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/elasticsearch/http.p12
```

Start Elasticsearch

```bash
$ ./bin/elasticsearch
```

Reset your `kibana_system` and `elastic` user passwords. Just set these to `changeme` for ease of use.

```bash
$ ./bin/elasticsearch-reset-password --url https://elasticsearch.local:9200 -u elastic -i
$ ./bin/elasticsearch-reset-password --url https://elasticsearch.local:9200 -u kibana_system -i
```

Activate a trial license for your Elastic stack

```bash
$ curl --cacert ./config/certs/ca/ca.cert -u elastic:changeme -X POST https://elasticsearch.local:9200/_license/start_trial\?acknowledge\=true
```

## Run Kibana pointed at SSL Elasticsearch

Add the following to `kibana.yml` in your Kibana snapshot’s `config` directory.

```yaml
elasticsearch.hosts: [https://elasticsearch.local:9200]
elasticsearch.ssl.certificateAuthorities: <elasticsearch location>/config/certs/kibana/elasticsearch-ca.pem
elasticsearch.username: kibana_system
elasticsearch.password: changeme

xpack.fleet.agents.elasticsearch.hosts: [https://elasticsearch.local:9200]
xpack.fleet.agents.kibana.host: http://kibana.local:5601

# This is necessary to configure a Logstash output later
xpack.encryptedSavedObjects:
  encryptionKey: "32 character string" # Use something like https://www.uuidgenerator.net/ to generate this value
```

Start Kibana

```bash
$ ./bin/kibana
```

## Set up Fleet Server

Add the fingerprint you generated earlier to the default ES output in your Fleet settings within Kibana. 

![Untitled](https://user-images.githubusercontent.com/6766512/163401371-5797407e-ff19-40d0-a993-e9f18a0cc554.png)

Also, add a second output or alter your default to point at `https://192.168.65.2:9200` so your dockerized agents can communicate with Elasticsearch, e.g.

![Untitled 1](https://user-images.githubusercontent.com/6766512/163401365-434dab2b-0a99-46fe-bea9-107cd481ce89.png)

Run a dockerized Fleet Server using the following

```bash
docker run \
  -e KIBANA_HOST=http://192.168.65.2:5601/ \ # 👈 Docker gateway IP
  -e ELASTICSEARCH_HOST=https://192.168.65.2:9200 \ # 👈 Make sure this is `https`!
  -e FLEET_SERVER_ENABLE=1 \
  -e FLEET_SERVER_SERVICE_TOKEN=<copy from fleet UI> \
  -e FLEET_SERVER_POLICY_ID=fleet-server-policy \
  -e FLEET_SERVER_ELASTICSEARCH_CA_TRUSTED_FINGERPRINT=<fingerprint generated earlier> \
  -p 8220:8220 docker.elastic.co/beats/elastic-agent:8.2.0-SNAPSHOT
```

Verify you’re receiving metrics data by visiting the `[Metrics System] Overview` dashboard in Kibana once your Fleet Server is running.

## Create a Logstash output in Kibana

Navigate to `Fleet -> Settings -> Outputs` and select `Add output`. Provide a name, your docker gateway IP (since Fleet Server is running on Docker and needs to communicate with your local instance of Logstash) including the port `5044` configured for your Logstash input, and the certificate files as follows:

1. Server SSL certificate authorities = contents of the `ca.cert` file we generated above
2. Client SSL certificate = `logstash.crt` file contents
3. Client SSL certificate key = `logstash.pkcs8.key` file contents

![Untitled 2](https://user-images.githubusercontent.com/6766512/163401367-1953b51a-4abb-4acc-b5b0-59676559af82.png)

## Configure Logstash

These instructions should be visible via the “View instructions” button shown above. 

Add the following to `<logstash>/config/pipelines.yml` at the top of the file.

```yaml
- pipeline.id: elastic-agent-pipeline
  path.config: "<some file location>/elastic-agent-pipeline.config"
```

Create the pipeline config file

```bash
$ touch <some file location>/elastic-agent-pipeline.config
```

Add the following to the pipeline config file

```
input {
  elastic_agent {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["<elasticsearch snapshot location>/config/certs/ca/ca.cert"]
    ssl_certificate => "<elasticsearch snapshot location>/config/certs/logstash/logstash.crt"
    ssl_key => "<elasticsearch snapshot location>/config/certs/logstash/logstash.pkcs8.key"
    ssl_verify_mode => "force_peer"
  }
}

output {
  elasticsearch {
    hosts => "https://elasticsearch.local:9200"
    api_key => "<Generated in Fleet UI>"
    data_stream => true
    ssl => true
    cacert => "<elasticsearch snapshot location>/config/certs/ca/ca.cert"
  }
}
```

## Run Logstash

Run Logstash via `./bin/logstash`

## Create an Agent Policy that uses the Logstash output

Use the Fleet UI to create a basic Agent Policy, and set the output to your Logstash output. 

![Untitled 3](https://user-images.githubusercontent.com/6766512/163401369-a7ec8dc1-e015-4cb9-a273-f5ca48dbc8b5.png)

You can add the `elastic_agent` integration as well.

## Run a dockerized Agent against the Logstash policy

Use Fleet’s “Add Agent” button to create a new agent. Copy the enrollment token value into the command below to spin up an Agent under your Logstash policy.

```bash
docker run --rm \
  -e FLEET_URL=https://192.168.65.2:8220 \
  -e FLEET_ENROLL=true \
  -e FLEET_ENROLLMENT_TOKEN=<copy from Fleet UI> \
  -e FLEET_INSECURE=1 \
  docker.elastic.co/beats/elastic-agent:8.2.0-SNAPSHOT
```

## Verify Logstash is receiving data

Run the following cURL request to verify Logstash is ingesting data

```bash
$ curl -XGET localhost:9600/_node/stats/events | jq .
```

You can omit `jq` if it’s not installed - it’s just a JSON parser to clean up the output. you should see a section in the output that looks as follows:

```
"events": {
    "in": 7145,
    "filtered": 7145,
    "out": 7145,
    "duration_in_millis": 800406,
    "queue_push_duration_in_millis": 0
  }
```

You can also revisit the metrics overview dashboard we checked above to ensure your Logstash agent’s metrics data is appearing.

**Comment by nchaulet** [comment]
> @joshdover We have attempted to use shortlinks before but the problem is that they cannot be versioned, so users will end up on the current documentation even if they are running an older release 🥲 

Could we use a shortlink specialy for 8.2 and replace it with a docLink for 8.3? I planned some time next week with @dedemorton to see how I can help building the doc here

**Comment by dedemorton** [comment]
I've opened this PR to set up a URL for the Logstash certs docs: https://github.com/elastic/observability-docs/pull/1795

The URL will be https://www.elastic.co/guide/en/fleet/<branch>/secure-logstash-connections.html

The location of the topic in the TOC is TBD, but the URL won't change.

**Comment by richardgilm** [comment]
> @dedemorton I don't see this on the docs project board. I wanted to make sure that we are prioritizing Logstash support in 8.2 as it's a highly sought after feature.
> 
> Also it needs to be marked Beta. I will follow up with an email on the details. thx

Should we expect an updated table of Supported Outputs for Fleet-managed Elastic Agent, marking Logstash as (in beta)?
https://www.elastic.co/guide/en/fleet/8.2/beats-agent-comparison.html#supported-outputs-beats-and-agent

**Comment by dedemorton** [comment]
@richardgilm Yup. Either I will update or @nimarezainia. Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team
We have validated doc for this feature at links:

**Comment by amolnater-qasource** [comment]
Hi Team
We have validated docs for this feature at links:
- https://www.elastic.co/guide/en/fleet/8.2/secure-logstash-connections.html#configure-ls-ssl
- https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html

Further we have reported 1 issue for a small conflicting information at link https://github.com/elastic/observability-docs/issues/1850

Hence, marking this as QA:Validated.
Thanks
