### ISSUE TITLE
Add documentation for new dedicated rules management page for Observability alerting rules

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1706]
## Description

A new dedicated rules management page for Observability alerting rules will be made available. This view and workflows will need to be documented. 

https://github.com/elastic/kibana/issues/119100

## Collaboration
- The docs team will lead producing the content, in close collaboration with the product team

**Contact Person:**
@mgiota 

## Suggested Target Release
8.2 (please check with @mgiota on what features on that new rule management page will be made available in 8.2)

## Stakeholders
@emma-raffenne 
@simianhacker 
@vinaychandrasekhar

**Comment by mgiota** [comment]
In which format will you provide us the newly generated documentation link?

The old link is defined in the code like this `docLinks.links.alerting.guide` and this gets eventually translated into https://www.elastic.co/guide/en/kibana/master/create-and-manage-rules.html. I am asking, because I want to know if we need to implement something on our side.

**Comment by emma-raffenne** [comment]
@mgiota 
First we need to write the documentation, once we have it, we will get the link to be updated in the code.

**Comment by mgiota** [comment]
@emma-raffenne Let me know if product team needs help from me regarding content generation.
