### ISSUE TITLE
Document Synthetics Private Locations

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2046]
## Description

https://github.com/elastic/uptime/issues/475 is adding Private Locations to Synthetics.  This makes use of Fleet and Agent (with the _complete_ image) and the updated Synthetics Integration to provide an Agent that can then be linked through as a private location.  This will effectively supersede the current behaviour of the Synthetics Integration, making it easier to manage monitors in the same way, whether they’re running on private locations, or through the service (i.e. the monitor configuration will be the same, simply with a list of locations, some of which may be public, and some of which may be private).

Further details on how to set this up can be found [here](https://github.com/elastic/uptime/issues/475#issuecomment-1196000788).  There are some additional updates in thir PR https://github.com/elastic/synthetics/pull/566.

Documentation should clarify there are limited scaling capabilities currently with Private Locations.

Note that there will be future work (tracked [here](https://github.com/elastic/kibana/issues/137508)) for auto migrating existing Synthetics Integrations to the new Private Locations mechanism (but this won’t be done in 8.4, and is currently planned for 8.5).

Once the docs are available (or ideally, when the URL is known), we can work on https://github.com/elastic/kibana/issues/137594 (which needs to be done for 8.4).

## Collaboration

- The docs team will lead producing the content

**Contact Persons:** @dominiqueclarke @lucasfcosta 

## Suggested Target Release

Will be made available for 8.4.0 (still under beta, as is all Synthetics)

## Stakeholders

@andrewvc, @drewpost, @dominiqueclarke

**Comment by paulb-elastic** [comment]
We should note in the docs that Private Locations will limit the concurrency of browser monitors to only run 2 at a time, and cannot be overridden.

Note that this was implemented in https://github.com/elastic/beats/pull/32564 and although that refers to being able to override this, this would be for plain Heartbeat, not for running it through Elastic Agent / Docker (which is how Private Locations are run).  It cannot be overridden for Private Locations, so is fixed at a concurrency of 2 for browser monitors.

**Comment by colleenmcginnis** [comment]
@paulb-elastic @hbharding  should "Private Locations" be capitalized or should it be "private locations"? It looks like in internal comms you're using "Private Locations" capitalized, but the UI uses lower case.

cc @gchaps

**Comment by paulb-elastic** [comment]
Apologies @colleenmcginnis that's probably my overzealous use of proper nouns.

Looking at the UI, it is using `Private locations` as the case

![image](https://user-images.githubusercontent.com/70908889/183637892-da2435d5-aa75-4974-9a95-e2795d1f771a.png)

I'd be more than happy to defer to your / @hbharding's expertise here.

**Comment by gchaps** [comment]
Our [writing guidelines](https://eui.elastic.co/pr_3350/#/guidelines/writing) say to use sentence case in UI copy, unless it is a proper noun.  Using "private locations' in this copy makes the text easier to read.

**Comment by colleenmcginnis** [comment]
>Synthetics UI still won’t be promoted in 8.4, so nothing to document for it yet
>_From: https://github.com/elastic/observability-dev/issues/2222#issuecomment-1199764612_

@paulb-elastic I'm confused about how to document private locations in the UI without documenting the updated UI, but maybe I'm misunderstanding what you mean above.

Right now we list two ways to initially [set up monitors](https://www.elastic.co/guide/en/observability/current/uptime-set-up.html): **Heartbeat** or **Elastic Agent + the Synthetics integration**. This document does **not** include:

* Adding a monitor using the `push` command because as far as I know that is only relevant to one type of monitor -- browser monitors -- and this doc is for all monitor types. (This is documented in [the section on writing synthetic tests](https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html) instead.)
* Adding a monitor using `Monitor management` > `Add monitor` because I thought that was part of the UI that we weren't going to document yet -- but let me know if that's wrong! 

In the original post, you mentioned:

>This makes use of Fleet and Agent (with the complete image) and the updated Synthetics Integration to provide an Agent that can then be linked through as a private location.

Based on this, I expected to see an option when creating a monitor via `Integrations` > `Elastic Synthetics` (v0.10.1) > `Add Elastic Synthetics`, but there is no field for specifying a location when adding the integration (like there is when using `Monitor management` > `Add monitor`). 

Where am I going wrong?

**Comment by paulb-elastic** [comment]
Apologies @colleenmcginnis if I’ve confused things.

> Synthetics UI still won’t be promoted in 8.4, so nothing to document for it yet

In the planning of 8.4 doc requirements, I just meant that the Synthetics UI won’t be available to users in 8.4, so there is no documentation that needs planning in for the 8.4 work.

Have you seen how Private Locations are set up? Maybe I should run through this on a Zoom so you can see how it works, and how the Agent Policy comes into this.

Let me know - I’d be happy to go through this.  Can do it later today if you’re available.
