### ISSUE TITLE
[Request] Observability overview: Guided Setup renaming

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-docs#2166]
## Description

![image](https://user-images.githubusercontent.com/4104278/188801386-7174a7d8-c60d-43f1-9b9c-b944046defa6.png)

![image](https://user-images.githubusercontent.com/4104278/188801411-dced03b4-505f-4855-b169-10a670d3b784.png)

Since we're introducing a Guided Setup design in Kibana as a complete experience, we will need to avoid confusing the user, and rename the existing data/integration status in the Observability overview page since this "Guided Setup" is not part of the new experience. We will want to keep the current implementation because it helps with further onboarding the user, but we will need to rename the button and flyout title and description to reflect the intended purpose. The individual data check descriptions do not need to change.

Example of the new experience where Guided Setup naming would appear for two separate features;

![CleanShot 2022-09-09 at 14 33 14](https://user-images.githubusercontent.com/4104278/189350893-eeb12c19-c5d8-4400-9386-0432383a87a8.png)

## Links

- [Figma file](https://www.figma.com/file/PlHFXOVSW5Uf7v13FN32PK/Updates-to-naming-and-components?node-id=209%3A21086)
- [Observability design issue](https://github.com/elastic/observability-design/issues/241)

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

@formgeist 

## Suggested Target Release

8.5/8.6 (at latest)

## Stakeholders

@elastic/observability-design @formgeist @elastic/unified-observability

**Comment by dedemorton** [comment]
IMO the naming of this button is misleading. As a user, I would expect something called "Integration status" to show me the status of integrations that are already installed rather than guide me through the installation/set up of additional integrations and features.

It also raises the expectation that users are familiar with what the term "integration" means. 

I think that's why we settled on "Guided setup" originally.

**Comment by formgeist** [comment]
I don't disagree that the current name works better than Integration status, but because Guided Setup will start to refer to the overall onboarding guides for Elastic, I find it necessary to differentiate this feature from the other. I realize that I didn't show off the screenshot that would show for users;

![CleanShot 2022-09-09 at 14 33 14](https://user-images.githubusercontent.com/4104278/189350761-f5875091-7ab2-4145-91b1-57dffa559760.png)

**Comment by dedemorton** [comment]
I'm not sure whether this question is still open for debate (since the PR was merged), but I wonder if any of the following text strings would work better?

Integration setup
Integration setup status
Setup status

**Comment by formgeist** [comment]
> I'm not sure whether this question is still open for debate (since the PR was merged), but I wonder if any of the following text strings would work better?

I didn't merge the changes in the PR, it was created by mistake 😅 

> Integration setup
> Integration setup status
> Setup status

I think are definitely better options. I considered "Setup help" or "Setup assistant", but that doesn't have the status reference that we're perhaps also seeking. "Getting started" is another possibility seeing as the main purpose of the feature is to help the user get setup with the relevant data in Observability. What do you think?

**Comment by dedemorton** [comment]
I think "Getting started" is really overloaded, so I would avoid.
"Setup help" sounds weird to my ear because it includes two words that could be verbs. 
"Setup assistant" is a bit better.

Let's ask @elastic/kibana-docs for their thoughts.

Here's a recap of  the options we've discussed. TBH, I'm not sure we've hit on the right phrasing yet.

Integration setup
Integration setup status
~Getting started~
Setup status
Setup help
Setup assistant

**Comment by gchaps** [comment]
I lean toward "Setup assistant". Kibana already has an "Upgrade assistant", which guides users through an upgrade.  "Setup assistant" is also used my Mac.  

@kellyemurphy Does this align with the copy you are working on for onboarding? Do you have any other suggestions?

**Comment by formgeist** [comment]
@kellyemurphy Sure, no problem! Let me schedule something in our calendars 👍

**Comment by formgeist** [comment]
@kellyemurphy @dedemorton Looking at our schedules, I think it's going to be difficult during the next week or so. If you have time to meet, feel free to, and then perhaps I can sync with @kellyemurphy next week if possible to finalize our decision?

**Comment by dedemorton** [comment]
Sorry I was on PTO last week. To save time, I'll second Gail's vote. I think "Setup assistant" is the best option here. @kellyemurphy You can make the final call based on how this fits in with the overall guided setup experience.

**Comment by kellyemurphy** [comment]
We ended up going with "Setup guide" for the overall onboarding, so I think we should avoid any similarities to that here. I do like the idea of using "assistant" to align with other parts of the UI. This is complicated because they aren't all apps, they aren't all features, and I don't know if any of these are actually integrations. 

How about one of these:

Data assistant (my top recommendation)
Integration assistant 
Integration assist
App assistant
App assist (Splunk uses this)
Observability assistant
Observability assist
O11y assistant (this probably won't fly, but it's cute)

**Comment by formgeist** [comment]
Thanks @kellyemurphy for the suggestions 👍 

> Data assistant (my top recommendation)

I think this fits the overall feature without confusing the user regarding the Guided Setup. This feature will evolve and perhaps we will decide to brand it differently later.

**Comment by formgeist** [comment]
Here are the resulting screens for the Data assistant change. Continue to track implementation in https://github.com/elastic/observability-design/issues/241. Closing this issue (feel free to re-open if there are other processes around this).

![image](https://user-images.githubusercontent.com/4104278/192290666-2e42d353-3e63-4f19-99f4-e353f06886fb.png)

![image](https://user-images.githubusercontent.com/4104278/192290697-9d7834f4-8f8e-47e6-8220-89a080ae91aa.png)

**Comment by dedemorton** [comment]
Love it! Nice work.

**Comment by formgeist** [comment]
Naming changed was merged in https://github.com/elastic/kibana/pull/141779
