### ISSUE TITLE
[Request] Functionbeat Deprecation 

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#2225]
## Description

*We intend to announce the deprecation plan or Functionbeat in 8.5. Th expectd end of support date will be 12 months later. This issue is to place an appropriate banner in the Functionbeat docs pages*

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will define with product team the structure and location, and the product team will provide the initial content

**Contact Person:**
*@nimarezainia*

## Suggested Target Release

*8.5*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
This deprecation notice should probably go on all the pages because "each page is the first page" from a user's perspective.

Of course, we will also want to add this deprecation to the 8.5 release notes. :-) 

We have a couple of options to add the notice: 

1. We can add a deprecation tag to every page. (I'm not proposing we use this text; just using it as an example):

![image](https://user-images.githubusercontent.com/14206422/194142663-bf0320c8-0d0f-4d6d-858e-bc19d746db33.png)

2. We can put a banner at the top of every page. This approach is less work because it's one file.

![image](https://user-images.githubusercontent.com/14206422/194142555-27ce64d4-7994-4184-bfeb-00954da19581.png)

**Comment by nimarezainia** [comment]
thanks @dedemorton I'll go with your expertise on this. Sounds like (2) is the way to go.
I know you put sample text above but it should read something like:

"Functionbeat will reach End of Support on 18th of October 2023. Users should consider moving their deployments to the more versatile and efficient Elastic Serverless Forwarder <link to serverless forwarder docs>."
