### ISSUE TITLE
[Synthetics] Document migrating from Synthetics Integration to Private Locations/Project Monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2257]
## Description

Building on top of https://github.com/elastic/observability-docs/issues/2149 and that we’ll be removing ZIP URLs in the future (via [kibana#137508](https://github.com/elastic/kibana/issues/137508), [kibana#137505](https://github.com/elastic/kibana/issues/137505) and [kibana#137501](https://github.com/elastic/kibana/issues/137501)), this requirement is to provide some information on how users can migrate from using the _legacy_ Synthetics Integration to set up monitors, over to Private Locations / Project Monitors.

## Collaboration
- The docs team will lead producing the content (with support from any of the team)

## Suggested Target Release
- This isn't needed to coincide with the 8.5 release, but there’s no need to wait for the 8.6 release.  This might be a good candidate to work on once all the content needed for the 8.5 release is done, before 8.6 work begins.

## Stakeholders
- @paulb-elastic @andrewvc @dominiqueclarke

**Comment by colleenmcginnis** [comment]
@paulb-elastic as I started working on this, a couple questions came up:

* Should we also have a migration guide for Heartbeat?
* Should we limit the scope just to migrating existing monitors using ZIP URLs to using Project Monitors and `push`? Should we also mention how the user can use the Uptime app UI for lightweight monitors and browser monitors via inline script instead of using the integration?
* What are the changes that need to be made to an existing project that was added via ZIP URL to make them work as Project Monitors? Off the top of my head I can think of:
  * They probably need to update the version of `@elastic/synthetics` they are using.
  * They (I think) need to configure the monitor (schedule, location, unique id, etc) in the code directly instead of in the integration UI.
  * They will need an API token in order to `push` monitors.
  * What else?
* Do you think it's helpful to have a side-by-side comparison (see _very rough_ mockup below)?

Here's a _very rough_ mockup of the direction we could take for a migration doc. Let me know what you think of the direction before I continue down this path.

![localhost_8000_guide_synthetics-migrate-from-integration html (5)](https://user-images.githubusercontent.com/10479155/204356371-46d41e9c-d6dc-40cc-a1a9-0d005c576bd4.png)

**Comment by paulb-elastic** [comment]
Thanks for the questions and thoughts @colleenmcginnis 

> migration guide for Heartbeat

I don't think we should do this quite yet as I think there are still too many configuration options [not possible](https://github.com/elastic/synthetics-dev/issues/159) with lightweight project monitors right now.

> Include inline scripts via the UI instead of using the integration

Yes, this is a good idea as we want people to stop using all of the capabilities of the Synthetics integration approach.  This will therefore need to include the lightweight monitors (which are all configured via the GUI for the integration approach) as well.

> What else is needed to migrate ZIP to project

I think you have a good list there.  I don't know if you want to link them to the other docs for what's needed for project monitors in general (like needing to `init` and needing an API key) - i.e. this isn't specifically because they are migrating, but because they will be using project monitors.

I haven't tried taking a ZIP and seeing what else might be needed, but your list seems right.  One thing to mention is that they will have created a default location and schedule as part of `init` so don't _have_ to set these when migrating them over.  Again, it might just be worth highlighting this and pointing them to the existing docs on how that's done (although I'd defer to your suggestion on the balance between duplicating content, or linking them to existing docs elsewhere).

> Side by side comparison

I really like this, this is a great idea.  I have some thoughts about wording etc. but appreciate this is a very rough initial draft.

**Comment by simranvaseer-qasource** [comment]
Hi @paulb-elastic

We have gone through this ticket and found that current changes are available in the doc.
[https://www.elastic.co/guide/en/observability/master/synthetics-migrate-from-integration.html#synthetics-migrate-integration-location](https://www.elastic.co/guide/en/observability/master/synthetics-migrate-from-integration.html#synthetics-migrate-integration-location)

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/212616952-bbb613ab-2325-4533-b2aa-fb42e20b2691.png)
![image](https://user-images.githubusercontent.com/102019374/212617069-b719313d-712f-43e7-a85a-492ac25e18bb.png)
![image](https://user-images.githubusercontent.com/102019374/212617148-d6195d67-fd28-4c63-8519-1135a749357a.png)


Please let us know if any further validations are required.
Thanks
