### ISSUE TITLE
[Fleet]: Sample Fleet Server installation commands not available.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#2313]
**Description:**
Sample Fleet Server installation commands not available for on-prem(self-managed) installation.

**Link:**
- https://www.elastic.co/guide/en/fleet/8.5/add-fleet-server-on-prem.html

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/199670179-1120acc5-e2b2-4158-98bf-d4809258c0c9.mp4

**What's working fine:**
For 8.2.0 sample commands are available:

https://user-images.githubusercontent.com/77374876/199670234-8f927d79-6bb4-40b7-9cab-866d8f3a3e73.mp4

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @dedemorton

**Comment by dedemorton** [comment]
We intentionally removed the command from the docs because it was getting out of sync with the product and was incomplete compared to the command that users can get from the in-product steps.

Closing, but feel free to re-open if you can point to specific examples of users who are confused because this command is not shown in the docs.

**Comment by amolnater-qasource** [comment]
Hi @dedemorton 
Thank you for the update.
We will be marking this as expected while documentation testing.

Thanks!
