### ISSUE TITLE
[REQUEST]: Support multiple Fleet Servers in Fleet UI

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#2343]
### Description

We are delivering the ability to configure a fleet server on a per policy basis. As described here: https://github.com/elastic/kibana/issues/137785

### Resources

https://github.com/elastic/kibana/issues/137785
https://github.com/elastic/fleet-server/issues/903

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @nimarezainia

**Stakeholders:**
@nimarezainia

**Comment by nimarezainia** [comment]
@dedemorton here is the doc with screenshots as a starter for multiple fleet servers: https://docs.google.com/document/d/1uzSwf7TVLLwH4s1p25Tzar5aDIou6khkF8vICbgc0Mw/edit?usp=sharing

in the near future we will be adding Proxy support per policy and I would like to enhance these docs to include the proxy as a section within as it applies to teh same deployment use case.

@kpollich & @nchaulet if you have the bandwidth please review this also in case I have missed something. thank you

**Comment by dedemorton** [comment]
@nimarezainia Just an FYI that Colleen is going to take over this work. I was hoping to get this done before Friday, but things have gone a bit sideways, and I think it would be better not to rush to get it done this week.

**Comment by colleenmcginnis** [comment]
@nimarezainia I'm trying to understand how your Google doc relates to the existing live Fleet Server docs. A couple initial questions:

* Does this change how [Deploy Fleet Server on-premises](https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html#deployed-on-prem) and [Deploy Fleet Server on-premises to work with a hosted Elasticsearch Service](https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html#fleet-server-on-prem-es-cloud) work? Or does this change introduce a fourth approach?
* Does this change remove the need for a "Load balancer" in the [diagrams in the live docs](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-on-prem.html) because the user specifies which individual agents roll up to which Fleet Servers? Or does it change _how_ the user uses a load balancer? I can't quite tell how these updates fit into the bigger picture based on your diagram in the [Google doc](https://docs.google.com/document/d/1uzSwf7TVLLwH4s1p25Tzar5aDIou6khkF8vICbgc0Mw/edit). Maybe like:
    <img width="1500" alt="fleet-server-on-prem-deployment" src="https://user-images.githubusercontent.com/10479155/205175499-61d63a11-7d90-4aab-827f-fbcae805a0ed.png">

**Comment by nimarezainia** [comment]
@colleenmcginnis this would apply to the cases where the fleet server is deployed on-premises (so the two sections that you mention). Nothing should change in the components we have in the diagrams (such as the load balancer). This feature is just making it easier for the user to have all the agents in a policy connect to the nominated fleet server in that policy.

**Comment by simranvaseer-qasource** [comment]
Hi @nimarezainia 

I have gone through this ticket and found that current changes are available in the doc.
[https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html](https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html)

Please let us know if any further validations are required.
Thanks
