### ISSUE TITLE
[REQUEST]: Adding links to Kibana docs for all ServiceNow connectors in the Create Alerts page

### ISSUE THREAD

**Issue by SubhrataK** [elastic/observability-docs#2382]
### Description

The Create Alerts page under Observability: https://www.elastic.co/guide/en/observability/current/create-alerts.html

is missing the mention and links to the Kibana docs for all Service Now connectors. Please add the following links and mentions in the doc under the Create Rules section:

ITSM connector: https://www.elastic.co/guide/en/kibana/current/servicenow-action-type.html
SecOps connector: https://www.elastic.co/guide/en/kibana/current/servicenow-sir-action-type.html
ITOM connector: https://www.elastic.co/guide/en/kibana/current/servicenow-itom-action-type.html

### Resources

https://elastic.slack.com/archives/C02FQULS9PX/p1668661154500179

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @SubhrataK 

**Stakeholders:** @amena-siddiqi

**Comment by dedemorton** [comment]
@SubhrataK Sorry it's taken us awhile to get to this issue because of competing priorities. I am not authorized to access the link that you provided (https://elastic.slack.com/archives/C02FQULS9PX/p1668661154500179) so I can't see the details related to this request.

When I look at the current version of the [Observability Alerting docs](https://www.elastic.co/guide/en/observability/8.12/create-alerts.html), I don't see _any_ links to the docs about connectors. Do you want me to add ServiceNow SecOps and ITOM to the list and make _all_ the connectors active links?

@lcawl Do you have any insight into why this page no longer point to the docs about connectors? Is there a reason why we don't want to do that anymore?
