### ISSUE TITLE
[Stack Monitoring] Docs pages for agent-based monitoring

### ISSUE THREAD

**Issue by matschaffer** [elastic/observability-docs#2602]
### Summary

For each supported service we should create a dedicated page (or section) describing how to set up the corresponding integration, what it can collect and where it is stored, or what additional resources if any are available. Given there is overlap with the metricbeat setup we can reuse some of the corresponding metricbeat documentation ([kibana example](https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html)).

### Links
- [Monitor Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitor-elasticsearch-cluster.html)
- [Monitor Kibana](https://www.elastic.co/guide/en/kibana/current/configuring-monitoring.html)
- [Monitor Logstash](https://www.elastic.co/guide/en/logstash/8.5/configuring-logstash.html)
- [Monitor APM](https://www.elastic.co/guide/en/apm/guide/current/monitor-apm.html)
- [Monitor Enterprise search](https://www.elastic.co/guide/en/enterprise-search/current/monitoring.html)
- Monitor Beats - [the complete list](https://www.elastic.co/guide/en/elasticsearch/reference/current/how-monitoring-works.html) and [auditbeat example](https://www.elastic.co/guide/en/beats/auditbeat/8.5/monitoring.html)
- [Stack Monitoring](https://www.elastic.co/guide/en/kibana/current/xpack-monitoring.html) page has an outdated list of products (missing APM and enterprise search)

**Comment by dedemorton** [comment]
## Doc impact [WIP]

This section provides an overview what needs to be added, changed, or validated. WIP because I need to view the demo and play around with the software to finalize this list.

We will be patching existing docs with new content rather than making extensive structural changes at this time. We might be able to leverage content from the "quick guide" I've created for https://github.com/elastic/observability-docs/pull/2564.

_Observability Guide_

- [ ] Add a stack monitoring topic to the obs guide at the same level as the other types of monitoring. This topic will basically be a link farm to all the existing content across the docs. It's not the best user experience, but will give users a starting point.

_Kibana Guide_

- [ ] Add new topic about monitoring with Agent.
- [ ] [Configure monitoring in Kibana](https://www.elastic.co/guide/en/kibana/current/configuring-monitoring.html) - needs to mention Elastic Agent
- [ ] [Collect Kibana monitoring data with Metricbeat](https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html#monitoring-metricbeat) - should point to Elastic Agent as an alternative
- [ ]  [View monitoring data](https://www.elastic.co/guide/en/kibana/current/monitoring-data.html) - validate

_Elasticsearch Guide_

- [ ] Add new topic about monitoring with Elastic Agent
- [ ] [Monitor a cluster](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitor-elasticsearch-cluster.html) - Update the jump list in the container topic
- [ ] [Monitoring overview](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-overview.html) - Needs to mention Elastic Agent and maybe show an agent-based diagram
- [ ] [How monitoring works](https://www.elastic.co/guide/en/elasticsearch/reference/current/how-monitoring-works.html) - Needs to mention Agent and include a link to the new content
- [ ] [Monitoring in a production environment](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-production.html) - Needs to mention Elastic Agent and include link to the new content
- [ ]  [Collecting Elasticsearch monitoring data with Metricbeat](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html) - Should mention Elastic Agent as an alternative
- [ ] [Collecting Elasticsearch log data with Filebeat](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-filebeat.html) - May need to update this to mention that this is not required if the integration collects logs (look into this)
- [ ] [Configuring indices for monitoring](https://www.elastic.co/guide/en/elasticsearch/reference/current/config-monitoring-indices.html) - May need to point out that this is not required when using Elastic Agent (not sure if there’s anything required for users to do for logs-* and metrics-* data streams)
- [ ] [Collecting monitoring data using legacy collectors](https://www.elastic.co/guide/en/elasticsearch/reference/current/collecting-monitoring-data.html) - May want to add Elastic Agent as a recommended way to collect stack monitoring data

_Logstash Reference_

- [ ] Add new topic about monitoring with Elastic Agent.
- [ ] [Monitoring Logstashl](https://www.elastic.co/guide/en/logstash/8.6/configuring-logstash.html) - Mention Elastic Agent as a way to monitor Logstash and point to the new topic.
- [ ] [Collect Logstash monitoring data with Metricbeat](https://www.elastic.co/guide/en/logstash/8.6/monitoring-with-metricbeat.html) - Mention Elastic Agent as an alternative way to monitor Logstash.
- [ ] [ Monitoring UI](https://www.elastic.co/guide/en/logstash/8.6/logstash-monitoring-ui.html) - Update screen captures

_APM Guide_

- [ ] [Monitor APM Server](https://www.elastic.co/guide/en/apm/guide/current/monitor-apm.html) - link under configuring Elastic Agent should probably point to the new topic that covers Agent rather than Metricbeat. Also verify that we still want to tell users to change settings in elastic-agent.yml (not sure for APM, but in general, we want folks to use the settings in Fleet).

_Enterprise Search Guide_

- [ ] [Monitoring](https://www.elastic.co/guide/en/enterprise-search/current/monitoring.html) - Maybe add a section about Agent and the Enterprise search integration to provide coverage similar to metricbeat?

**Comment by dedemorton** [comment]
All the work here is done except the enterprise search docs, which will be updated by that team. I'll leave this issue open, but I'm done with my part here.

**Comment by dedemorton** [comment]
Closing now because the enterprise search doc changes are tracked in https://github.com/elastic/enterprise-search-team/issues/4153
