### ISSUE TITLE
[REQUEST] Alerting Documentation Improvements

### ISSUE THREAD

**Issue by emma-raffenne** [elastic/observability-docs#2605]
# Context

This is related to the o11y alerting documentation included in the _Observability guide_:

- [o11y Alerting](https://www.elastic.co/guide/en/observability/current/create-alerts.html)

It is **NOT** related to the Alerting section of the _Kibana guide_ that corresponds the foundational alerting services provided by the stack (ResponseOps team from Platform).

# Proposed Improvements

- Structure the Alerting documentation starting with an introduction as entry page and separate pages for each feature (rules, alerts) so new pages can be added as new features are being delivered and the user can find their way according to what they try to achieve.
- Separate o11y alerting services documentation from app specific features, e.g. creation of rule per rule type.
- Cross-link app specific features documentation from/to alerting and the corresponding app documentation
- Provide content oriented to best practices and use cases our users can relate to

**Comment by dedemorton** [comment]
Some of these changes were made in the serverless docs, but never made it back into the classic/stateful docs because everyone was in a rush to meet our big Oct milestone. As we work on improving the Alerting docs, we need to sync them up with serverless, where possible: https://docs.elastic.co/serverless/observability/alerting

**Comment by dedemorton** [comment]
Closing this issue because the structural changes have been addressed. We still need to provide "content oriented to best practices and use cases our users can relate to" but to accomplish this goal, we need a lot more input from the development team. I'll track that work as part of the meta issue I've created around improving the alerting docs: https://github.com/elastic/observability-docs/issues/3622.
