### ISSUE TITLE
[REQUEST]: Getting started docs don't seem to refer to most of our capabilities

### ISSUE THREAD

**Issue by SeanHeelan** [elastic/observability-docs#3185]
### Description

If I land at the Elastic home page looking for docs on observability the journey is 

https://www.elastic.co/ -> https://www.elastic.co/guide/index.html -> (Get Started) -> https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-observability.html

This brings me to a page that looks as follows:

![Screenshot 2023-08-30 at 10 08 05](https://github.com/elastic/observability-docs/assets/1920339/ce271ee2-e747-444a-b7ee-20c1de33ac8a)

I can't tell if I have missed something or not, so please let me know if I have, but this page doesn't seem to describe most of our Observability features or use cases. In fact, most of the links on the page are to things unrelated to observability. The 'Get started' docs only discuss logs and metrics. 

Is there some other landing page that we expect users to end up on when they come looking for observability? If not, should we have a think about what sort of message we want to give to users that arrive at elastic.co looking for observability, and then go to our docs? Is there a better way to show off what we offer?  

### Resources

N/A

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

Unsure this applies here. I wanted to just note the issue, so someone can tell me if it actually is an issue or not, and figure it out if so =)

**Comment by bmorelli25** [comment]
Thanks for opening this issue, @SeanHeelan. This has been a common complaint ever since we added the documentation landing page. We've received pushback in the past that has prevented us from updating where the "Observability" graphic links to. However, I've just finished a series of updates that should make this experience much better for users.

Can you please go to our [documentation homepage](https://www.elastic.co/guide/index.html) and try the journey again? Hopefully the experience is a lot better now.

**Comment by bmorelli25** [comment]
I'm going to close this as complete. Please feel free to reopen if something still looks wrong.
