### ISSUE TITLE
[Custom Threshold Rule] Document the new alert details page for the Custom Threshold rule

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#3550]
### Description

An alert details page has been created focusing on the logs use case, that needs to be documented

### Resources

The main issue for the UI changes are in https://github.com/elastic/kibana/pull/174031
The project, that includes more context and links to other tasks, is https://github.com/elastic/actionable-observability/issues/47

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Same in stateful and serverless

### What release is this request related to?

8.13

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @maryam-saeidi and @benakansara 

**Stakeholders:**
- @vinaychandrasekhar

**Comment by paulb-elastic** [comment]
@bmorelli25 yes, that's right

**Comment by dedemorton** [comment]
@bmorelli25 FYI.... I need to bump this to the next sprint for a few reasons:

- The original sizing for this work was inaccurate, and the work will require more time than anticipated. Why? There's more complexity to this page than I realized when this issue was triaged. For example, there are several factors that influence what appears on this page, including: what is the use case? Is there more than one condition specified in the rule? Does the user have a license? I'll need to either document this page very generically, or provide information that's tailored to specific use cases. I'll need to more time to interview some folks to figure out what info users need to know.
- The new page is being released as a beta feature in 8.13. It will be improved in 8.14, so is likely to change.
- In the past, (AFAIK) we haven't provided documentation for alert details pages (just generic docs under the topic about [viewing alerts](https://www.elastic.co/guide/en/observability/8.12/view-observability-alerts.html#view--alert-details)). Does it make sense to start documenting beta-level pages when some GA-level pages (like the Latency threshold alert details) are not yet documented?
- All of the concepts around alerting are pretty new to me, so there's also a learning curve to overcome.
- This sprint is a short one for me

**Comment by maryam-saeidi** [comment]
@dedemorton FYI, we have this [document](https://docs.google.com/document/d/1PwtoUHI5uywwVankUuSZOx6bisVIRiwv8lQHF4Yjji0/edit#heading=h.n9ma7qad1wq4) that shows the information that we show in the alert details page and based on what condition. This is just FYI, I imagine we might not want to cover everything in the document, but I thought maybe it would help to understand covered scenarios and for creating a better screenshot for the page. :)

**Comment by dedemorton** [comment]
Thanks @maryam-saeidi. I'm wondering...given the current state of docs about our alert details pages (currently only documented at a high level), do you think it makes sense to provide detailed docs about the custom threshold alert details page before it's GA? If so, I'll put this at the top of my list when I'm back April 1.

**Comment by maryam-saeidi** [comment]
> Thanks @maryam-saeidi. I'm wondering...given the current state of docs about our alert details pages (currently only documented at a high level), do you think it makes sense to provide detailed docs about the custom threshold alert details page before it's GA? If so, I'll put this at the top of my list when I'm back April 1.

@vinaychandrasekhar what do you suggest about documenting alert details page before it is GA?

**Comment by dedemorton** [comment]
Some more scoping/ideas from discussion with Jason. 

The docs should focus on answering questions user have rather than trying to document the UI. Should answer questions like:

What is log rate analysis?
What does the alertis history show and how is it calculated?

Docs should provide context that we're unable to provide in the UI.

**Comment by vinaychandrasekhar** [comment]
> @vinaychandrasekhar what do you suggest about documenting alert details page before it is GA?
Custom Threshold alert details page will be a GA very soon, so I'd proceed with documenting it. In general though, I'd prioritize documenting our GA capabilities first before addressing beta/Preview ones.
