### ISSUE TITLE
Clarify indicator for APM availability SLO

### ISSUE THREAD

**Issue by graphaelli** [elastic/observability-docs#3913]
In https://www.elastic.co/guide/en/observability/current/slo-create.html#apm-latency-and-availability-sli the latency threshold is described as:

> Create an indicator based on the APM data that you received from your instrumented services and a latency threshold.

clearly indicating latency as the metric.  I expect omission of the exact field as currently implemented is deliberate to keep things simple, that seems fine.  Even so, the availability description could be more specific, currently:

> Create an indicator based on the APM data received from your instrumented services.

availability should be specific about using the transaction outcome (success/failure) as the indicator, and perhaps a note about the impact of unknown outcomes.

**Comment by grabowskit** [comment]
Add a line in the documentation for SLO Availability that the field being used in event.outcome - "availability is defined in terms of transaction error rate, in the implementation it's using the APM event.outcome field. Available metric is calculated by calculating the rate of success divided by (success + failure)"

**Comment by grabowskit** [comment]
cc: @dedemorton

**Comment by dedemorton** [comment]
@grabowskit I'm a little confused. If availability is defined in terms of the transaction error rate, then why does the calculation look at the success rate? I haven't really worked with APM data so maybe I am misunderstanding something here? I agree that the docs are super vague and need clarification. 

Would it be accurate to say something like this instead:

 **APM availability**
Create an indicator based on the availability of your instrumented services.
Availability is determined by calculating the percentage of successful transactions (`event.outcome : "success"') out of total transactions.

--- 

I also propose that we modify the description of latency to say something like:

**APM latency**
Create an indicator based on latency data received from your instrumented services and a latency threshold.

(I guess it would be OK to say "APM data" here but I don't think that's necessary because "instrumented services" imply plus the title imply that you are using APM.)

Let me know what you think.

**Comment by dedemorton** [comment]
Note that I've put up a PR for you to review: #3953. Rather than responding here, you can comment directly in the PR review. Thanks!
