### ISSUE TITLE
[Request]: Change "APM" to "Applications" in topics that describe how to navigate the Observability app

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#4070]
### Description

https://github.com/elastic/kibana/pull/188409 changes "APM" to "Applications" in the Observability nav for 8.16.

In the docs, we need to make sure any menu paths that refer to this option are updated...plus any screen captures that show the side nav (hopefully we don't have any of those, but we should check).

### Resources

https://github.com/elastic/kibana/pull/188409

### Which documentation set does this change impact?

Stateful only

### Feature differences

In this case, stateful is aligning with serverless.

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @kpatticha 

**Stakeholders:**

**Comment by colleenmcginnis** [comment]
Waiting on #4230 to avoid conflicts.

**Comment by colleenmcginnis** [comment]
A couple questions:

* In Serverless, we use the term _Applications UI_ instead of _APM UI_ because the side navigation used _Applications_. Should I also update references to the _APM UI_ in the stateful docs? Thoughts @bmorelli25? 
* Will the cross-solution side navigation also change from _APM_ to _Applications_? Right now it looks like it still uses _APM_ (see image below).

    ![Image](https://github.com/user-attachments/assets/9527ddb5-2e18-4beb-89be-80b1f8e1c8f7)

**Comment by bmorelli25** [comment]
> Will the cross-solution side navigation also change from APM to Applications? Right now it looks like it still uses APM (see image below).

@kpatticha do you know if there are plans to update this throughout the product?
