### ISSUE TITLE
[Request]: Update Hosts documentation to reflect GA

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#4216]
### Description

We will be moving Hosts to general availability in our next serverless/stateful releases (9th/16th Sept serverless : 8.16 for stateful).

This issue is to update the [stateful documentation](https://www.elastic.co/guide/en/observability/current/analyze-hosts.html) and [serverless documentation](https://www.elastic.co/docs/current/serverless/observability/analyze-hosts) to reflect it is now under general availability.

_Note : The stateful docs don't need to be changed until 8.16_

### Resources

**Related Doc Issues**

- [ ] https://github.com/elastic/observability-docs/issues/4145
- [ ] https://github.com/elastic/observability-docs/issues/4079
- [ ] https://github.com/elastic/observability-docs/issues/3862

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

No differences

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @smith @crespocarlos

**Comment by alaudazzi** [comment]
@roshan-elastic 
For [serverless documentation](https://www.elastic.co/docs/current/serverless/observability/analyze-hosts) the fix is ready for review in https://github.com/elastic/observability-docs/pull/4266.
For [stateful documentation](https://www.elastic.co/guide/en/observability/current/analyze-hosts.html) we can track the same doc fix in  https://github.com/elastic/observability-docs/issues/4267  until 8.16.
