### ISSUE TITLE
Update Observability landing page

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#4248]
### Update landing page before serverless

Add links to GA

https://www.elastic.co/guide/en/observability/current/index.html

**Comment by dedemorton** [comment]
I hope I have interpreted this issue correctly (my assumption here is that you want the landing page to link to the serverless docs). I guess another possible interpretation is that you want the serverless docs landing page to have the same level of detail (where possible) as the Obs Guide page. I'm going with the simplest interpretation because I _think_ that's what you want.
