### ISSUE TITLE
[Logs] Updated docs for Logs UI deprecation

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#4315]
The log stream component will be hidden by default and there's going to be a Kibana advanced setting to enable it. Our docs need to be updated to explain this.

[Kibana guide](https://www.elastic.co/guide/en/kibana/current/observability.html) also needs to be updated

[Project link](https://github.com/elastic/observability-dev/issues/3242)

**Comment by mdbirnstiehl** [comment]
@tonyghiani currently the docs show the same message as the UI:

![Image](https://github.com/user-attachments/assets/46cc7116-ab8f-426e-80a9-73a919842d4a)

I think we should change the title of this page to make it more obvious that it's about the Logs Stream app, and update the note that Stream will be deactivated by default and that users will have to turn it on, and give those steps. 

I assume we want to be pretty assertive that this is not the preferred method and users should be switching to Logs Explorer. I will also move this down in the navigation hierarchy so it's not so prominent. 

Other than that, I'll update the Kibana guide to focus more on Logs Explorer and get rid of Stream references. I think I've already removed most references to Logs Stream elsewhere, but I'll make sure. 

Anything else I'm missing?

**Comment by tonyghiani** [comment]
@mdbirnstiehl everything you listed sounds good! Let me know if you need guidance on the steps to take to re-enable it and what the newly introduced setting hides in Kibana (only Logs Stream app and Logs Stream Dashboard panel), I agree we should put emphasis on this not being a recommended option 👌

**Comment by mdbirnstiehl** [comment]
@tonyghiani It would be great if you could provide the steps for re-enabling Logs stream, thanks!

**Comment by tonyghiani** [comment]
@mdbirnstiehl Sure, here is a resume of the situation once the user upgrades to the new version.
- There is a new Advanced Setting named **Logs Stream** (`observability:enableLogsStream`) which defaults to `false` on the stateful/cloud deployments and is not available in serverless ones (still, defaults to `false` behind the scene).
  - When `observability:enableLogsStream` is false, the Logs Stream page route is not registered, and neither is its deep link for global search.
  - When `observability:enableLogsStream` is false, the panels list on Dashboard won't show anymore the option Logs Stream (Deprecated) to prevent usage of this embeddable in new dashboards. The embeddable is still registered for retro-compatibility with active dashboards, and it now has a callout explaining the status of this embeddable (unmaintained/deprecated).

To re-enable the above features disabled by the new setting, the user should:
- Visit `Management` -> `Advanced Settings` -> Search for `Logs Stream`
- Enable the setting, save the changes and reload the page.
- Visit the `Observability` -> `Logs` and che the Stream entry is again available in the sidebar
- Search in global search should display the stream as a result
- The legacy dashboard panel **Logs Stream (deprecated)** should be displayed again.

This setting is not available in serverless and the default behaviour is the same, where Logs Stream has not been available since the beginning.
