### ISSUE TITLE
[Logs] Document the central logs source setting

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#4316]
A new central setting as described in https://github.com/elastic/logs-dev/issues/138 should be introduced. Once in place, it can be used in progressively more places throughout the observability solution.

[Project Link](https://github.com/elastic/observability-dev/issues/3498)

**Comment by Kerry350** [comment]
@mdbirnstiehl No problem. I'll write up some bullet points tomorrow on what this affects and how 👍

**Comment by Kerry350** [comment]
From a high level what we've done is added a new advanced setting (called Log sources) which now influences how multiple Observability solutions access logs data (rather than having disjointed methods - hardcoded indices lists etc). The hope is that this brings consistency to data access and less surprises for users (https://github.com/elastic/logs-dev/issues/138).

![Image](https://github.com/user-attachments/assets/28ea272b-83d8-4e40-9666-686d2f7cf536)

Right now these changes affect the following UIs:

- Logs UI settings: 

![Image](https://github.com/user-attachments/assets/04917720-010d-4303-8a87-ea8592ecf186)

The setting is now the default option associated with the logs UI settings. This also means the setting still influences the indices queried in log threshold rules **unless the user has manually changed to "indices" or "data view"**. Those two options are now deprecated. (https://github.com/elastic/logs-dev/issues/170)

- For the two deprecated options above a migration assistant option was added, with a "quick resolve" option, to help migrate users to the advanced setting option with their Logs UI settings (https://github.com/elastic/kibana/issues/186824):

![Image](https://github.com/user-attachments/assets/3aa4b3c9-9526-4db5-934e-11d782c65d68)

- Both the log categories and log anomalies ML jobs now read their indices from this setting (under choose indices) (https://github.com/elastic/logs-dev/issues/168)

![Image](https://github.com/user-attachments/assets/d6e63816-d39e-4850-b0da-407a2182a538)

- In Logs Explorer this is now the default data source (e.g. "All logs") (https://github.com/elastic/logs-dev/issues/169):

![Image](https://github.com/user-attachments/assets/a5e0e407-28bf-45b9-8939-0ccf6f8833f0)

- The Observability AI Assistant specific advanced setting has been removed in favour of, and consolidation with, this setting for choosing where to access logs data (https://github.com/elastic/logs-dev/issues/167)

- In Discover this setting is now used as part of the context resolution process to determine if we are viewing logs data (https://github.com/elastic/logs-dev/issues/171)
