### ISSUE TITLE
[Onboarding] Update the Quickstart doc for monitoring of Hosts.

### ISSUE THREAD

**Issue by akhileshpok** [elastic/observability-docs#4563]
The 'Quickstart: Monitor hosts with Elastic Agent' doc should be updated.

- This functionality is available as GA in 8.16.
- This functionality is available in all Elastic deployment models.
- This functionality can auto-detect 14 Integrations in 81.6.
- Under 'Collect your data' the screenshot in step 3 needs to be updated.
- Under 'need to scan your host again', we should specify the name of the auto-detect script as well as the folder in which it can be found.
- The 'Visualise your data' section needs to be updated to include the additional Integrations that can now be supported OOTB.

Please reach out to @thomheymann or @akhileshpok for clarifications on any of the above items.

**Comment by dedemorton** [comment]
These changes are up for review in https://github.com/elastic/observability-docs/pull/4582.

Here's a description of how I've handled the requested items:

>This functionality is available as GA in 8.16.

Removed technical preview flag.

>This functionality is available in all Elastic deployment models.

Added this to the requirements section.

>This functionality can auto-detect 14 Integrations in 81.6.

Removed the related limitation.
 
>Under 'Collect your data' the screenshot in step 3 needs to be updated.

Replaced screenshot. We're not sure whether we want to provide a screenshot at all in this section because the UI has historically been quite volatile. Your input would be appreciated.

>Under 'need to scan your host again', we should specify the name of the auto-detect script as well as the folder in which it can be found.

Added

>The 'Visualise your data' section needs to be updated to include the additional Integrations that can now be supported OOTB.

Added a row to indicate that additional assets are available. We should avoid listing all the assets because the list is likely to grow and get stale...plus it would be very long for a topic that we are calling a "quickstart."

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/4582
