### ISSUE TITLE
[Request]: Rework APM decision tree diagram

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#4669]
### Description

Rework the [APM decision tree diagram](https://www.elastic.co/guide/en/observability/current/apm-getting-started-apm-server.html#_help_me_decide) based on feedback from @eedugon: 

> Great doc!! I have a question about this box:
> <img width="432" alt="image" src="https://github.com/user-attachments/assets/ffbbfa9a-c53f-478a-a07f-b8cd736b78bd">
> 
> `Do you want to use other integrations` sounds too generic when it probably wants to ask `Do you want to use other integrations together with the APM Server` or `in the same APM Server`?

> I have a couple of extra questions, just in case you consider them useful, feel free to ignore them if wanted ;)
> 
> <img width="886" alt="image" src="https://github.com/user-attachments/assets/8287688c-6298-4a69-9c85-ae14e081a0f6">
> 
> What does it mean `centrally` and `on the edge` in the context of the question? I haven't seen any explanation about that in the rest of the doc. It feels like `on the edge` means `where the apps are running, far away from Elastic Stack`, and `centrally` might mean then `closer to the elastic stack`, but I feel a bit lost with both answers.

See initial feedback from @simitt in https://github.com/elastic/observability-docs/pull/4599#issuecomment-2516923915. 

### Resources

https://github.com/elastic/observability-docs/pull/4599#issuecomment-2516483247

### Which documentation set does this change impact?

Stateful only

### Feature differences

N/A

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @eedugon 

**Stakeholders:** @simitt

**Comment by eedugon** [comment]
About `central` and `edge` concepts, @simitt explained to me that:

- `on the edge` means multiple APM servers in the `edge servers` where applications run (so the applications have direct and faster access to APM server). In this scenario there's usually no connectivity between users browsers and APM servers, that's why this architecture wouldn't be compatible with RUM.

- `central` means running APM server in a location accessible by apps and users browsers, which is compatible with RUM.

In my opinion, the entire question about `central` and `edge` is **not related** with the decision of running the agent with the binary or as fleet managed, as in both options (`on the edge` and `centrally`) the user could run APM server binaries or Fleet managed agents).

It's true that `on the edge` means multiple APM servers and it's probably better from operational point of view to run them as `managed` (so the configuration could be changed in all at once directly from Fleet).

But none of that is obvious to the user or is explained in the docs.

Maybe we could add a (`*`) in the `on the edge` arrow explaining what on the edge means and why we recommmend `Fleet Managed` on that scenario, not being mandatory.
