### ISSUE TITLE
Update/consolidate Fleet kibana.yml settings

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#758]
There is a page for `xpack.fleet.*` settings here: https://www.elastic.co/guide/en/kibana/current/fleet-settings-kb.html

But it is now outdated. I also thought it was odd to have this away from the rest of the Fleet docs, like https://www.elastic.co/guide/en/fleet/current/fleet-settings.html.

Here's a list of valid settings:
`xpack.fleet.enabled`: see Kibana settings doc
`xpack.fleet.registryUrl`: see Kibana settings doc
`xpack.fleet.registryProxyUrl`: see https://github.com/elastic/kibana/pull/78648
`xpack.fleet.agents.enabled`: enable or disable central management of agents
`xpack.fleet.agents.elasticsearch.hosts`
`xpack.fleet.agents.elasticsearch.ca_sha256`
`xpack.fleet.packages`
`xpack.fleet.agentPolicies`

**Comment by Zacqary** [comment]
This PR contains usage examples of `packages` and `agentPolicies`: https://github.com/elastic/kibana/pull/96588

### `packages`

This is a list of integration packages to be installed when the Fleet app starts up for the first time. Required props are:
- `name`: the name of the package
- `version`: either an exact semver, or the keyword `latest` to fetch the latest package version

### `agentPolicies`

This is a list of agent policies to configure when the Fleet app starts. Required properties are:

- `name`: a name of the policy
- `id`: a number or string acting as a unique ID for this policy

Optional properties are:

- `description`: A text description of this policy
- `namespace`: a string identifying this policy's namespace, for advanced use cases
- `monitoring_enabled`: A list of either or both the keywords `logs` or `metrics`
- `is_managed`: if `true`, this policy will not be editable by the user, and can only be changed by updating the Kibana config
- `is_default`: if `true`, this will be considered the default agent policy
- `is_default_fleet_server`: if `true`, this will be considered the default agent policy for the Fleet Server
- `package_policies`: A list of policy integrations to add to this policy
  - `name`: **(required)** the name of the integration policy
  - `package`: **(required)** An object containing
    - `name`: the name of the integration package associated with this policy
  - `description`: a text string describing this integration policy
  - `namespace`: a string identifying this policy's namespace
  - `inputs`: An array that overrides any default input settings for this policy's package. Follows the same schema as integration inputs, with the exception that any object in `vars` can be passed `frozen: true` in order to prevent that specific var from being edited by the user.
