### ISSUE TITLE
7.14 Documentation Release

### ISSUE THREAD

**Issue by andresrc** [elastic/observability-docs#771]
### General release tasks

- Observability
  - [x] What's new in 7.14 
- Agent
  - [x] Upgrade guide 
- Fleet and Agent
  - [x] Release notes
- APM Server
  - [x] Release notes 
  - [x] Breaking changes 
  - [x] Upgrade guide 
- Beats
  - [x] Release notes
  - [x] Breaking changes 
  - [x] Upgrade guide
- Stack docs
  - [x] Copy of Observability What's new 
  - [x] Copy of APM Server breaking changes 
  - [x] Copy of Beats breaking changes

**Comment by dedemorton** [comment]
I've added Fleet and Agent to the list here because we are currently creating release notes manually. I've started a PR [here](https://github.com/elastic/observability-docs/pull/896), but we'll need more input, especially about changes in Elastic Agent. Usually I just harvest content from the Kibana docs for any Fleet-related items.
