### ISSUE TITLE
Document Gold+ agent actions

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#880]
Document the behavior of this features in Basic and Gold+. Explain use cases where they'd want the Gold+.

![image](https://user-images.githubusercontent.com/6370704/126523526-8a8edc52-eabe-455c-a0f0-8945442fb8ea.png)

**Comment by dedemorton** [comment]
@mostlyjason Historically there has been strong resistance to documenting subscription-related details in the docs. Instead we've been asked to point to the [subscriptions page](https://www.elastic.co/subscriptions) as the source of truth. 

If we need to describe what selective updates and unenrollment are, we can do that in the docs and add an xpack badge (which links to the subscriptions page). 

We just need to know what you want us to say because I'm not really sure what "selective" means in these contexts.

**Comment by mostlyjason** [comment]
> If we need to describe what selective updates and unenrollment are, we can do that in the docs and add an xpack badge (which links to the subscriptions page).

Yep that's what I mean. Describe what they are, the behavior and use cases they can achieve with them. "Selective" means they can choose to apply these actions to one or more agents, and they can select which agents to apply it to. It's basically bulk select actions:

![image](https://user-images.githubusercontent.com/6370704/128902511-fe0525db-c85d-446e-aa74-76152e6ccc38.png)

This will likely be changing in early 8.x so we might want to timebox our effort on this one. I imagine it's just a small section of the Fleet page docs?

**Comment by mostlyjason** [comment]
I have a google document with some more context on use cases. I can't link it here but I can provide it on request.
