### ISSUE TITLE
Document how to set data retention / ILM policies for integrations

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#986]
## Description

When users create integrations, they control the retention of their data through ILM policies set on index templates. It's not obvious how to do this because we abstract away these lower level concepts in the UI. We should document how these concepts connect to integrations and how users can set their data retention.

## Collaboration

* [ ] The docs team will lead producing the content
* [x] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

*(We need to have a contact person in the product/development team to provide information about how the item to be documented works.)*
@hop-dev 

## Suggested Target Release

7.16

## Stakeholders

*(Please list any stakeholders for this issue.)*
@mostlyjason @leehinman 

Related: https://github.com/elastic/kibana/issues/108554

**Comment by mostlyjason** [comment]
FYI @jethr0null since we discussed this in the data lifecycle working group

**Comment by hop-dev** [comment]
In the simplest case, if a user wished to customise the index lifecycle for a data

**Comment by hop-dev** [comment]
On https://github.com/elastic/kibana/issues/108554 there has been some discussion about a more basic approach for customising data retention across all namespaces using the supplied `@custom` component templates.

Currently by default, each data stream that is part of a package has the `metrics` index lifecycle policy specified in the matching index template, this means that the policy cannot be overridden by specifying it in the `*@custom` component template. One exception to this default behaviour is if a package defines their own ILM policy as part of installation (for example the APM package).

Nicholas raised moving the ILM policy to a component template on [this PR](https://github.com/elastic/kibana/pull/111197) which would enable a user to override with their own policy. In which case we would be able to consider documenting this option.

The more comprehensive (and complicated!) approach will be to use index templates which are scoped to the namespace, I'll follow with more detailed steps.

**Comment by hop-dev** [comment]
**Rough steps for configuring an ILM policy for a data stream in a namespace**

If a user wishes to have custom data retention for data streams in a particular namespace then index templates must be used.

In most cases the data streams and index templates used by a package follow a standard pattern, however there are packages such as APM which define their own ILM policies and apply them to data streams which will make the documentation more complex. 

Here I document the steps to introduce a custom retention policy for network data collected by the system package, I have a dev and production namespace and I only wish to change the retention in `production` .  Users would have to repeat this process for each data stream within an integration.

Before these steps I created an ILM policy called `10m-rollover` which rolls over every 10 mins.

1. (optional) First you can use the data streams view in fleet to see which data streams the system package uses in production

<img width="1633" alt="Screenshot 2021-09-07 at 15 07 02" src="https://user-images.githubusercontent.com/3315046/132402573-13634403-2f9f-4102-a82d-45749e54f6f9.png">


2. You can see the system network data stream, to view further information about this data stream I can go to `stack management > index management > Data Streams (tab)` and search for the data stream, note that the data stream name is prepended by its type, e.g `metrics-` in this case

<img width="1367" alt="Screenshot 2021-09-07 at 15 11 10" src="https://user-images.githubusercontent.com/3315046/132401908-d336c741-cdc0-4eb0-a0cc-b2ee1d4ecb73.png">

3. Clicking the data stream allows me to see the index template used by the data stream `metrics-system.network-production`, click the index template  to view the template details.

<img width="1626" alt="Screenshot 2021-09-07 at 15 11 25" src="https://user-images.githubusercontent.com/3315046/132402621-c630776b-eb6b-4bd1-aa91-c7d09d9cbd5d.png">

4. In order to set a custom ILM policy for the production namespace we must clone the index template and use an index pattern which includes the namespace, to clone the index template click manage > clone

<img width="1632" alt="Screenshot 2021-09-07 at 15 12 04" src="https://user-images.githubusercontent.com/3315046/132402655-6d0d9650-ba29-4268-a0ed-02f97e08540d.png">

4. We must now change some settings for our new index template
    1. set the name to `metrics-system.network-production`
    2. set the index pattern to `metrics-system.network-production*`
    3. set the priority to 250
    4. remove `managed` and `managed_by`from the `_meta` data
    5. Under index settings, specify the name of the ILM policy you want to use in index.lifecycle.name, in this case I am changing it to `10m-rollover` 
    
    <img width="1631" alt="Screenshot 2021-09-07 at 15 16 21" src="https://user-images.githubusercontent.com/3315046/132403005-c4d0cf22-0c28-467d-8cfc-3efd9d719bef.png">
    
4. Create the index template

5. (optional) we can now see that the data stream is using our new index template and ilm_policy by showing it in dev tools `GET /_data_stream/metrics-system.network-production`

6. The ilm policy will only take effect for new indices, therefore we must either wait for a rollover (30d or 50GB by default) or force a rollover using the rollover API `POST /metrics-system.process-production/_rollover/`(note they could also manually apply the ILM policy to the backing index?)

**Comment by hop-dev** [comment]
@jen-huang on step 4 (iv.) above I recommend removing `managed` and `managed_by` when a user is overriding the index template for an integrations data stream (as the template is now managed by the user) do you agree with this?

**Comment by andresrc** [comment]
@mostlyjason can you describe the expected collaboration here? We recommend using the provided issue template.

**Comment by mostlyjason** [comment]
@andresrc I updated the description to include the new template format.

@leehinman I tagged you as a stakeholder in the data lifecycle mgmt working group. The goal for this it to document the current process for setting ILM policies for integrations, and we'll refine the UX for this in a later release. Would be nice to get your review on the content above.

**Comment by hop-dev** [comment]
@mostlyjason @joshdover I have laid out instructions for the two options we have here in a very rough way here:

https://gist.github.com/hop-dev/3e7798fd06c13a9acf36594aa797d4ba

before I create draft documentation we need to decide whether we are going to document option 1 or 2 (or both), I'll include a high level description here but more detail can be found in the gist above:

- **option 1** - use `*@custom` component templates to set an ILM policy for a data stream across all namespaces, this option is only available for integrations installed by kibana 7.16.

- **option 2** - use index templates to set an ILM policy for one (or all) namespaces, slightly more complicated but version agnostic I believe.

Both options involve the user making changes per-datastream which isn't ideal but I don't think can be avoided.

**Comment by mostlyjason** [comment]
@hop-dev @joshdover Offering users two different ways seems like we are making the decision process more complex for users. Is there a way we can recommend a single solution that solves most users' needs? When we implement our medium term solution in the UI, which of this approaches will we implement? That might be best from a long term perspective.

From a user needs perspective, I think we need the ability to have different ILM policies per namespace. The whole point of using namespaces is to partition different use cases or teams. For example, I want to retain my production logs for a week but my test environment logs for 24 hours. Another example is that team A wants to retain data for a week and team B wants it for 24 hours. 

I'd advocate either going the index template route or change how we set up the component templates to allow namespace support. What is the UX impact of this decision or is it purely technical? Would it impact the ability to upgrade templates over time? Would it help to set up some time to discuss the options live?

**Comment by joshdover** [comment]
> I'd advocate either going the index template route or change how we set up the component templates to allow namespace support. What is the UX impact of this decision or is it purely technical? Would it impact the ability to upgrade templates over time? Would it help to set up some time to discuss the options live?

In order to support namespace-specific customizations, we'll need to create a duplicate index templates and component templates for each namespace x data stream. Where we are right now, I doubt we want to be creating these by default since it will result in a very large number of templates for each integration that is installed. There are both technical and UX issues with creating such a large number of templates out of the box:
- It creates UX issues in the Index Management UI that are likely solvable (eg. filtering out managed templates by default), however it also adds quite a bit of noise to the `/_cat/templates` API and other template APIs. We could also consider filtering out managed templates from such APIs by default, but it would be considered a breaking change in Elasticsearch and would need to be considered very carefully.
- From a technical standpoint, I believe there is an upper bound to the amount of data that Elasticsearch's "cluster state" can reliably handle. This is where all cluster-wide data is stored, including index templates. That said, I think we need to benchmark this or get some assistance from the Elasticsearch team here to determine the actual limitations.

The workaround would be for Fleet to create the namespace-specific templates on-demand as users opt-in to customizations that require them. This is essentially what option (2) is documenting how to do manually.

All that said, I think we need to test these assumptions and really see at which point these UX and Elasticsearch performance problems begin to arise. We can then determine how to proceed with the the long-term path forward. Our implementation would be far simpler, less likely to break, and easier to support and document if we created all the namespace-specific template in all scenarios. IMO, we should try to find a long-term path forward that allows that option.

> When we implement our medium term solution in the UI, which of this approaches will we implement? That might be best from a long term perspective.

Back to this question, I think the answer right now is we'll almost certainly need to either have namespace-specific templates or modify how templates work in some way to avoid that need but still be able to deliver this feature (which feels unlikely to me at this point).

I think it'd be ok to proceed with option (2), even though it is more complicated. I suspect that we'll need to have logic that detects if a user has a template that overrides what they set in our UI (once we have it) and we can handle any manually created templates based on these docs in the same way as other user-created templates.

**Comment by joshdover** [comment]
Yesterday we discussed the different options and need for further investigating for the long-term solution here, but we didn't make a decision on what to do for phase 0 for 7.16. @mostlyjason any opposition to moving forward with option (2)? I believe it's likely to be compatible with any long-term option we end up choosing and gives user on 7.16 the most flexibility to use namespace-specific ILM policies.

**Comment by bmorelli25** [comment]
Hey everyone! I'll be the technical writer helping out with this issue. Thanks for all of the work so far on this.

@hop-dev Thanks for the draft! I'll take a look and let you know if I need anything else.

@joshdover The link Jason provided is probably a safe bet. If we need to move the content later I can set up redirects.
